name: SSH key
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022
    name: generate ssh key
    steps:    
      - id: step_set_output
        run: |
          $filename = "foo"
          $filepath = Join-Path $PSScriptRoot $filename
          ssh-keygen -t ed25519 -f $filepath -q -N ""

