name: SSH key
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022
    name: generate ssh key
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install winget
        uses: Cyberboss/install-winget@v1

      - id: run_script
        run: |
          winget install "openssh"
          ssh -V
          node .\scripts\sshkey.mjs

      # - id: step_set_output
      #   run: |
      #     $filename = "foo"
      #     $filepath = Join-Path $PSScriptRoot $filename
      #     ssh-keygen -t ed25519 -f $filepath -q -N ""
      #     get-content $filepath
