name: Test
on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to release'
        required: true
      quality:
        description: 'Quality'
        required: true
        type: choice
        options: 
        - insiders
        - stable
        default: stable
      uploadRelease:
        description: 'Create GitHub and DockerHub Release'
        type: boolean
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build dependencies 
    outputs:
      quality: ${{ steps.step_set_output.outputs.quality }}
    steps:    
      - id: step_set_output
        run: |
          set -e
          echo "${{ github.event.inputs.uploadRelease }}"
          echo "${{ github.event.inputs.uploadRelease == true }}"
          echo "${{ github.event.inputs.uploadRelease == false }}"
          echo "::set-output name=quality::${{ github.event.inputs.quality }}"

  another:
    needs: [test]
    uses: ./.github/workflows/another.yml
    with:
      quality: ${{ needs.test.outputs.quality }}
      stable: ${{ needs.test.outputs.quality == 'stable' }}
